[project]
name = "exla"
version = "0.1.0"
description = "Exla SDK for model optimization for edge"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools]
packages = ["exla"]
