[project]
name = "exla"
version = "0.1.0"
description = "Exla SDK for model optimization for edge"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clip-client>=0.8.3",
    "clip-server>=0.8.3",
    "openai>=1.61.1",
    "pillow>=11.1.0",
    "psutil>=6.1.1",
]

[tool.setuptools]
packages = ["exla"]
