[project]
name = "exla-sdk"
version = "0.1.0"
description = "EXLA SDK for hardware-optimized ML models"
authors = [
    {name = "Viraat Das", email = "virat@exla.ai"}
]
dependencies = [
    # Core dependencies that everyone needs
    "pillow",
    "psutil",
    "requests",
    "typing-extensions",
    "pydantic"
]

[project.optional-dependencies]
# Model-specific dependencies
clip = [
    "clip-client",
    "clip-server"
]

deepseek = [
    "transformers>=4.34.0",
    "accelerate"
]

resnet = [
    "torchvision",
    "tqdm"
]

mobilenet = [
    "torchvision"
]

# Hardware acceleration dependencies - these will be auto-selected during install
_cuda = [
    "torch>=2.0.0",
    "cuda-python",
    "vllm"
]

_jetson = [
    "torch>=2.0.0",
    "Jetson.GPIO",
    "jetson-stats",
    "jtop",
    "tensorrt"
]

_cpu = [
    "torch",
]

# Convenience groups
all-models = [
    "exla-sdk[clip]",
    "exla-sdk[deepseek]",
    "exla-sdk[resnet]",
    "exla-sdk[mobilenet]"
]

[build-system]
requires = ["hatchling", "setuptools"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["exla"]

[project.urls]
repository = "https://github.com/exla-ai/exla-sdk" 
