[project]
name = "exla-sdk"
version = "0.1.0"
description = "EXLA SDK for hardware-optimized ML models"
authors = [
    {name = "Viraat Das", email = "virat@exla.ai"}
]
dependencies = [
    "clip-client",
    "clip-server",
    "openai",
    "pillow",
    "psutil",
    "vllm",
    "torch",
    "transformers",
    "accelerate",
    "fastapi",
    "uvicorn",
    "pydantic",
    "requests",
    "typing-extensions"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["exla"]

[project.urls]
repository = "https://github.com/exla-ai/exla-sdk" 
